replicaCount: 2

image:
  repository: user-management-api
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: user-api.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  enabled: true
  auth:
    username: userapp
    password: userapppassword
    database: userdb
  primary:
    persistence:
      size: 8Gi

configmap:
  app:
    APP_ENV: production
    DATABASE_HOST: "{{ .Release.Name }}-postgresql"
    DATABASE_PORT: "5432"
    DATABASE_NAME: userdb
    DATABASE_USER: userapp

secret:
  app:
    JWT_SECRET: change-me-in-production
    DATABASE_PASSWORD: userapppassword
