apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-management.fullname" . }}-config
  labels:
    {{- include "user-management.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap.app | nindent 2 }}
