apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-management.fullname" . }}-secret
  labels:
    {{- include "user-management.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.app }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
